language: cpp
dist: bionic
compiler: g++
sudo: required

before_install:
  - sudo add-apt-repository ppa:beineri/opt-qt-5.12.0-bionic
  - sudo apt-get update

install:
  - sudo apt-get install qt512base 

before_script:
  - QTDIR="/opt/qt512"
  - PATH="$QTDIR/bin:$PATH"
  - source /opt/qt512/bin/qt512-env.sh
  - qmake Tibi__SharingOnLAN.pro

script:
  - make
