language: cpp
dist: bionic
compiler: g++
sudo: required

before_install:
  - sudo add-apt-repository -y ppa:beineri/opt-qt-5.12.0-bionic
  - sudo apt-get update

install:
  - sudo apt-get install -y qt512base 
  - sudo apt install -y libgl1-mesa-dev

before_script:
  - QTDIR="/opt/qt512"
  - PATH="$QTDIR/bin:$PATH"
  - source /opt/qt512/bin/qt512-env.sh

script:
  - mkdir buildTibi
  - cd buildTibi
  - qmake ../Tibi__SharingOnLAN.pro
  - make
